### ISSUE TITLE
switch theme

### ISSUE THREAD

**Issue by Chathula** [lgcolella/gatsby-starter-developer-blog#10]
can you add or explain a way to switch the theme? there are two `.less` files. but the way you have done this, hard to do a switch based on user input and storing it in `localStorage` and do the theme switch. 

any idea on this?

**Comment by luigi-colella** [comment]
As explained in the [README](https://github.com/lgcolella/gatsby-starter-developer-blog#how-to-change-themes), to switch theme you have to only import one of the `.less` them file that you prefer (from this [folder](https://github.com/lgcolella/gatsby-starter-developer-blog/tree/master/src/style/themes)) or create a new one (that basically means define needed Less variables [here](https://github.com/lgcolella/gatsby-starter-developer-blog/blob/master/src/style/global.less)).

**Comment by Chathula** [comment]
> As explained in the [README](https://github.com/lgcolella/gatsby-starter-developer-blog#how-to-change-themes), to switch theme you have to only import one of the `.less` them file that you prefer (from this [folder](https://github.com/lgcolella/gatsby-starter-developer-blog/tree/master/src/style/themes)) or create a new one (that basically means define needed Less variables [here](https://github.com/lgcolella/gatsby-starter-developer-blog/blob/master/src/style/global.less)).

am talking about adding functionality to do that. Need to a toggle button in website to do that. What will be the best way?

I need to have a dark, light theme switcher in my site.

**Comment by lgcolella** [comment]
Probabily the best and quickest way to achieve this is creating 2 sets of CSS variables, one for light theme and one for the dark one and put them in the body
```css
body {
    --theme-text: black;
}

body.dark {
    --theme-text: white;
}
```
and define each component that requires a specific rule in this way
```css

**Comment by luigi-colella** [comment]
A fine and quickest solution to achieve this may be is creating 2 sets of CSS variables, one for light theme and one for the dark one and put them in the body. I suggest you to use the same variables from `.less` theme files.

```css
body {
    --theme-text: black;
}

body.dark {
    --theme-text: white;
}
```
We can simply toggle a class selector like `.dark` to enable the variables of one of two themes (the button for the switch and its logic should be in a React Component).

Then we need to define the style of each component that requires a specific rule in this way

```css
.my-component {
    color: @theme-text;
    color: var(--theme-text);
}
```
We set the `color` property by a Less variable for first to provide a fallback for browser that does not support the CSS variables (you can check them [here](https://caniuse.com/#feat=css-variables)).

**Comment by lgcolella** [comment]
test

**Comment by lgcolella** [comment]
test2

**Comment by luigi-colella** [comment]
I close the issue since there were no further replies.
