### ISSUE TITLE
Add gatsby-plugin-i18n support?

### ISSUE THREAD

**Issue by blopa** [lgcolella/gatsby-starter-developer-blog#4]
Any chances of adding `gatsby-plugin-i18n` support for this starter? I actually tried myself for a couple of hours, but I couldn't make it work, I'm still new to Gatsby.

I think it's way nicer to have `pages/about.en.js` than `pages/about/index.en.js`, same for posts.

Thank you.

**Comment by luigi-colella** [comment]
Sure, I'll add the plugin and I'll add some pages as example asap.

**Comment by blopa** [comment]
Thanks! I ended up adding my own translation logic. But I still think that would be useful to your template, which is already really nice btw, thanks for sharing it.

**Comment by luigi-colella** [comment]
Plugin added.
